### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by magneticflux-** [Pattonville-Robotics/Common-Code#14]
We should license this so that other teams can use it and so it's truly open-source. I suggest GPLv3 or LGPLv3. Brought up in OpenFTC/OpenFTC-app#11.

**Comment by pieperm** [comment]
I agree, there's a lot of useful tools in `Common-Code` and I think some teams would like having access to it.

As for the type of license: [https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project](url)

> You may also want to consider the communities you hope will use and contribute to your project:
> Do you want your project to be used as a dependency by other projects? Probably best to use the most popular license in your relevant community. For example, MIT is the most popular license for npm libraries.

Does GPLv3 happen to be popular in the FTC open-source community? Or is there another reason?

**Comment by magneticflux-** [comment]
I'm particularly fond of GPL and LGPL because of the protections against closed-source derivations of open-source libraries. In essence, they require that all modifications distributed must also have their source distributed or easily accessible. GPL requires that users of the library adhere to that too, whereas LGPL only requires direct derivatives of the library to do so. I'm reluctant to go with, for example, the MIT license because while it's completely open and free, it offers no protections against the possibility of closed-source (but publicly available) projects using our copyrighted code. Since this is a library, the LGPL seems like the best all-around choice to me.
