### ISSUE TITLE
EncoderDrive motor stalls before reaching end value

### ISSUE THREAD

**Issue by LAtimes2** [Pattonville-Robotics/Common-Code#2]
I have a theory on why the motors stall sometimes in moveInches or rotateDegrees. I had the same thing happen with my NXT robot motors.

In RUN_TO_POSITION mode, the motor controller slows down the motor as it approaches the desired encoder value. It can reduce the power too much and the motor stalls before reaching the encoder value.

The way I solved it, in the "while (!reachedTarget)" loop, I make sure the encoder values are changing for each motor (if current == previous for x iterations, it is stalled). If a motor stalls, I set the power to a larger value (maximum or original?) to start it up again.

Info on RUN_TO_POSITION (http://ftcforum.usfirst.org/showthread.php?7024-Modern-Robotics-Motor-Controllers):

In RUN_WITHOUT_ENCODERS mode, the controller is simply applying a ratio of full voltage to the motor, so 0-1 spans 0 to 100% output voltage. And you will get what the motor gives you using this range. As with all motors it depends on load, and battery voltage.

Once we move over to RUN_USING_ENCODERS or RUN_TO_POSITION, the assumed “Top Speed” is based on the original TETRIX motors, and is stated to be 1000 degrees per second, or 4000 encoder counts per second. This seems reasonable at about 160 RPM.

So a request for 50% power (or more accurately 50% speed) will result in a measured speed of 2000 counts per second (CPS). The controller will attempt to regulate the power to obtain this speed. It will max out the voltage if that’s what’s required to reach 2000 CPS under a heavy load.

My own tests have shown that RUN_USING_ENCODERS are RUN_TO_POSITION are far from consistent in how they apply this “Top Speed”.

In RUN_USING_ENCODERS, the top speed seems to be clipped at about 3550 CPS (88%), and RUN_TO_POSITION is clipped at about 2560 CPS (65%).

**Comment by magneticflux-** [comment]
I don't think that this is the problem because our motors stall mid-movement. We're also giving them sufficiently high RPM values, but not enough to max the motors out. The issues occurs at the very beginning of the movement, after a brief correct movement.

**Comment by Ovec8hkin** [comment]
What logic did you use inside the while(!reachedTarget) loop to catch whether or not a motor hasn’t moved for x iterations?

The least we can do is try it and see if it helps. It might at least significantly decrease the probability of stalls occurring in the future.

**Comment by magneticflux-** [comment]
@LAtimes2 Could you make changes and create a pull request? Make a class extending the encoder drive class that has the test code so we can drop it in.

**Comment by LAtimes2** [comment]
If it is happening at the beginning, it may be the order of the commands. I'm not clear which command starts the motors running - setTargetPosition or setPower? Modern Robotics has a recent youtube video (https://www.youtube.com/watch?v=V8KfMyZrfhA&t=264s) that shows setPower before setTargetPosition.
In either case, one possible solution is to restart the sequence if the target hasn't been reached and the motors are not moving (via isBusy or stall detection).

**Comment by magneticflux-** [comment]
@LAtimes2 I can test the order of commands. If that doesn't work, I'll add a check for stalling. The issue is, our bug isn't reliably reproducible. I'll add any non-invasive fixes and we'll see if it ever happens again.

**Comment by magneticflux-** [comment]
Reopen if issue is still present.
